### ISSUE TITLE
Add a notebook about different resampling methods

### ISSUE THREAD

**Issue by pnuu** [pytroll/pytroll-examples#18]
Add a notebook that demonstrates all the different resampling methods available in Pytroll. For each method, show how to use them directly with Pyresample, and also the corresponding call via Satpy.

**Comment by djhoese** [comment]
I would prefer separate notebooks for the satpy versus pyresample examples. I'm worried the pyresample examples might be a little confusing since we don't have a consistent interfaces for all of the resampling methods (pyresample 2.0!).

**Comment by pnuu** [comment]
And that also clarifies the structure if I add a new directory for Pyresample examples.
