### ISSUE TITLE
ValueError: No reader(s) named: ['safe_msi']

### ISSUE THREAD

**Issue by sehHeiden** [pytroll/pytroll-examples#26]
I I try to open Satellite data from the Sentinel2 with pysat.
Im am using satpy version 0.20.0 installed with anaconda channel conda-forge on windows.

When I use: 

`                files = find_files_and_readers(base_dir=path,
                                               reader='safe_msi')`

I get the error:

> ValueError: No reader(s) named: ['safe_msi']

Is the reader name outdated? It it the folder? I Almost tried any level of subfolders... 

I tried it out with data of the processing level 1C and 2A.

**Comment by djhoese** [comment]
Which example is this specifically?

The reader should be `"msi_safe"` (swap the names). We must have missed a couple when fixing the reader names after trying to standardize them. If it still doesn't work for you after that then I'll let the other satpy devs help as I have little experience with this reader.

**Comment by sehHeiden** [comment]
Thanks! With your help and installing some additional packages. Everything is running.

I did ha a look at:

> https://github.com/pytroll/pytroll-examples/blob/master/satpy/Sentinel%202%20MSI%20true%20color.ipynb
