### ISSUE TITLE
coastline/borders

### ISSUE THREAD

**Issue by Tsironisa** [pytroll/pytroll-examples#38]
Hi, i would like some help. i want to add coastline or/and country bordes in my scenes from netCDF data.i could get it with pycoast onr geoviews
any help or simple code
Thanks in advance

**Comment by mraspaud** [comment]
@Tsironisa is your netcdf data satellite data? and in this case which data? In any case, pycoast should be able to help you when you get you data as a pillow image, and then you can look here on how to add the coastlines on top of the image: https://pycoast.readthedocs.io/en/latest/high_quality_contours.html

**Comment by Tsironisa** [comment]
Yes it is satellite data from severi instrument

**Comment by Tsironisa** [comment]
cw = ContourWriterAGG('/home/esn/data/gshhs') 
cause i cant find the correct path to ContourWriterAGG but i have the aggdraw and cartopy installed.
sorry for my lame question i am quite niw to this

**Comment by mraspaud** [comment]
@Tsironisa you need to provide the path to *your* directory here: `cw = ContourWriterAGG('/your/path/to/gshhs')`
you can download the coastlines as explained here: https://pycoast.readthedocs.io/en/latest/installation.html

**Comment by Tsironisa** [comment]
i worked like a charm
i cant thank you enough
Have a great day cause you made mine a great one
