### ISSUE TITLE
On-the-fly decompression of hrit files not working

### ISSUE THREAD

**Issue by difrancosimone** [pytroll/pytroll-examples#39]
Hi everyone,

i'm triyng to use the on-the fly decompression of hrit files on satpy 0.23.0 with python 3.8 and Ubuntu 18.04 LTS.

I correctly build xRITDecompress utility and setup the XRIT_DECOMPRESS_PATH environment variable with the absolute path inside, but if i try to run the following code:
satpy.find_files_and_readers(base_dir='../raw_data/hrit', start_time=datetime(2020, 10, 6, 12, 15),
                               end_time=datetime(2020, 10, 6, 12, 15),
                               reader='seviri_l1b_hrit')
i got the errror:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/venv/lib/python3.8/site-packages/satpy/readers/__init__.py", line 430, in find_files_and_readers
    raise ValueError("No supported files found")
ValueError: No supported files found
Hrit folder listing:
H-000-MSG4__-MSG4________-WV_073___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000014___-202010061215-C_
H-000-MSG4__-MSG4________-IR_087___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-IR_120___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-IR_108___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-WV_062___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000006___-202010061215-C_
H-000-MSG4__-MSG4________-IR_120___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-IR_016___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-VIS008___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-VIS008___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-IR_097___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000010___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000024___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000019___-202010061215-C_
H-000-MSG4__-MSG4________-WV_073___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-VIS006___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-IR_097___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-IR_039___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-WV_062___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-VIS006___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000004___-202010061215-C_
H-000-MSG4__-MSG4________-IR_097___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-WV_062___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-IR_039___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-IR_120___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-VIS008___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-IR_134___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-IR_016___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-IR_097___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-IR_134___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000017___-202010061215-C_
H-000-MSG4__-MSG4________-IR_134___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-VIS006___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-VIS006___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-IR_120___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-IR_120___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-WV_073___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-VIS006___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-IR_108___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-IR_016___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000001___-202010061215-C_
H-000-MSG4__-MSG4________-WV_073___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-IR_087___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-IR_087___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000007___-202010061215-C_
H-000-MSG4__-MSG4________-IR_097___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-VIS008___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-WV_073___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-IR_016___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-WV_062___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-VIS008___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-WV_062___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-IR_039___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-IR_087___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000018___-202010061215-C_
H-000-MSG4__-MSG4________-IR_039___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-IR_134___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-IR_108___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-IR_108___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000013___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000012___-202010061215-C_
H-000-MSG4__-MSG4________-IR_087___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-WV_073___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-IR_087___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-WV_062___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000016___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000005___-202010061215-C_
H-000-MSG4__-MSG4________-IR_039___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-IR_108___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-IR_134___-000002___-202010061215-C_
H-000-MSG4__-MSG4________-VIS008___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-VIS006___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-IR_087___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-IR_016___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-VIS008___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000002___-202010061215-C_
H-000-MSG4__-MSG4________-WV_062___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000008___-202010061215-C_
H-000-MSG4__-MSG4________-IR_097___-000004___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000009___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000011___-202010061215-C_
H-000-MSG4__-MSG4________-IR_108___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-IR_134___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-WV_062___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-IR_108___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000023___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000021___-202010061215-C_
H-000-MSG4__-MSG4________-VIS006___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-IR_134___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000015___-202010061215-C_
H-000-MSG4__-MSG4________-IR_108___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-IR_039___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-IR_016___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-_________-PRO______-202010061215-__
H-000-MSG4__-MSG4________-IR_039___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-IR_097___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000022___-202010061215-C_
H-000-MSG4__-MSG4________-_________-EPI______-202010061215-__
H-000-MSG4__-MSG4________-IR_120___-000006___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000020___-202010061215-C_
H-000-MSG4__-MSG4________-IR_087___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-IR_016___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-IR_097___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-IR_120___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-IR_134___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-IR_039___-000003___-202010061215-C_
H-000-MSG4__-MSG4________-VIS006___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-IR_120___-000007___-202010061215-C_
H-000-MSG4__-MSG4________-VIS008___-000001___-202010061215-C_
H-000-MSG4__-MSG4________-HRV______-000003___-202010061215-C_
H-000-MSG4__-MSG4________-IR_016___-000008___-202010061215-C_
H-000-MSG4__-MSG4________-WV_073___-000005___-202010061215-C_
H-000-MSG4__-MSG4________-WV_073___-000004___-202010061215-C_

Thank you in advance.
Simone

**Comment by mraspaud** [comment]
@difrancosimone I suppose you solved it, since you closed the issue?

**Comment by difrancosimone** [comment]
Dear mraspaud, 

yes i solved adding the file absolute path in environ variable instead of directory(contains the executable) path.

Thank you and regards.
